"""v0.2 initial schema: users, documents, pages, facts, snapshots

Revision ID: edb1eb3c08b3
Revises: 
Create Date: 2026-07-05 04:49:20.175896
"""
from alembic import op
import sqlalchemy as sa


revision = 'edb1eb3c08b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=True),
    sa.Column('raw_available', sa.Boolean(), nullable=False),
    sa.Column('company_name', sa.String(length=256), nullable=True),
    sa.Column('ticker', sa.String(length=32), nullable=True),
    sa.Column('report_type', sa.Enum('ANNUAL', 'INTERIM', 'QUARTERLY', 'PROSPECTUS', 'OTHER', name='reporttype'), nullable=False),
    sa.Column('report_period', sa.String(length=64), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('is_scanned', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PARSING', 'EXTRACTING', 'READY', 'FAILED', name='documentstatus'), nullable=False),
    sa.Column('status_detail', sa.Text(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_table('extracted_facts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=256), nullable=True),
    sa.Column('report_type', sa.String(length=32), nullable=True),
    sa.Column('report_period', sa.String(length=64), nullable=True),
    sa.Column('category', sa.Enum('INCOME_STATEMENT', 'BALANCE_SHEET', 'CASH_FLOW', 'BUSINESS', 'GUIDANCE', 'MANAGEMENT', 'RISK', name='factcategory'), nullable=False),
    sa.Column('concept_id', sa.String(length=64), nullable=True),
    sa.Column('metric_name', sa.String(length=128), nullable=False),
    sa.Column('metric_label', sa.String(length=128), nullable=True),
    sa.Column('raw_label', sa.String(length=256), nullable=True),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('value_text', sa.String(length=256), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('source_page_number', sa.Integer(), nullable=True),
    sa.Column('report_section', sa.String(length=128), nullable=True),
    sa.Column('source_text_snippet', sa.Text(), nullable=True),
    sa.Column('source_bbox_json', sa.String(length=128), nullable=True),
    sa.Column('source_table_cell_reference', sa.String(length=128), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('extraction_method', sa.String(length=64), nullable=True),
    sa.Column('extraction_timestamp', sa.DateTime(), nullable=False),
    sa.Column('version_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_facts_concept_id'), 'extracted_facts', ['concept_id'], unique=False)
    op.create_index(op.f('ix_extracted_facts_document_id'), 'extracted_facts', ['document_id'], unique=False)
    op.create_table('pages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('words_json', sa.Text(), nullable=False),
    sa.Column('tables_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parse_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('fact_count', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('note', sa.String(length=256), nullable=True),
    sa.Column('facts_json', sa.Text(), nullable=False),
    sa.Column('summary_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parse_snapshots_document_id'), 'parse_snapshots', ['document_id'], unique=False)
    op.create_index(op.f('ix_parse_snapshots_user_id'), 'parse_snapshots', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parse_snapshots_user_id'), table_name='parse_snapshots')
    op.drop_index(op.f('ix_parse_snapshots_document_id'), table_name='parse_snapshots')
    op.drop_table('parse_snapshots')
    op.drop_table('pages')
    op.drop_index(op.f('ix_extracted_facts_document_id'), table_name='extracted_facts')
    op.drop_index(op.f('ix_extracted_facts_concept_id'), table_name='extracted_facts')
    op.drop_table('extracted_facts')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
